### ISSUE TITLE
Test failure on master

### ISSUE THREAD

**Issue by rpdelaney** [twolfson/sexy-bash-prompt#72]
I'm getting a test failure on master right now:
```
ryan at mothership in ~/src/shell/sexy-bash-prompt on master
$ ./test/run.sh
# ERRORS OCCURRED. STDERR OUTPUT:
`sexy_bash_prompt_get_git_status` !== "⬡" on an unpushed and unpulled branch with a tracked non-origin remote Expected untracked unpushed-unpulled to have no tracked origin but it did not
```

**Comment by twolfson** [comment]
What version of `git` are you running?

**Comment by rpdelaney** [comment]
```
$ git --version
git version 2.11.1
```

**Comment by twolfson** [comment]
Hmm, we recently tested fine on `2.11.0`:

https://travis-ci.org/twolfson/sexy-bash-prompt/jobs/190083828#L410

Maybe it's a regression in `2.11.1` itself? I'll kick off a new Travis CI job to triage

**Comment by twolfson** [comment]
Alright, new job started here:

https://travis-ci.org/twolfson/sexy-bash-prompt/builds/202784264

**Comment by rpdelaney** [comment]
Looks like your job passed. Weird...

**Comment by twolfson** [comment]
Yep, on `2.11.1` like yourself =/

https://travis-ci.org/twolfson/sexy-bash-prompt/jobs/202784266#L385

Maybe something is different in your global/local `.gitconfig`? Can you paste it here?

```bash
git config --list
# To isolate source, we can use `--server`, `--global`, and `--local` but let's start here
```

**Comment by rpdelaney** [comment]
Here's the output from `git config --list`: http://sprunge.us/gNHI

**Comment by twolfson** [comment]
I tried to reproduce the error by wiping my global `git` config (backed up in `dotfiles` for sanity) and adding all your options but I had no luck =/

```bash
< ~/.gitconfig
# ...
git config --global --add 'core.excludesfile' '/home/ryan/.config/git/gitignore_global'
git config --global --add 'core.whitespace' 'trailing-space,space-before-tab'
git config --global --add 'core.filemode' 'true'
git config --global --add 'core.symlinks' 'true'
# ...
make test
# All tests passed!
```

When did this issue start occurring for you?

**Comment by rpdelaney** [comment]
The other day I had an idea for something to add to the prompt, so I checked the tests are passing before I started work. I can't tie it to any state changes in my configuration. I guess I'll just do my work and submit a PR, and we'll see if it builds in Travis.

**Comment by twolfson** [comment]
If you want to try debugging/iterating locally on the issue, I suggest using either a Vagrant box or Docker container as a sandbox:

# Vagrant
Bulkier of the 2 options due to spinning up a whole VM whereas Docker is the same OS but with middleware to lock in actions

1. Install Vagrant from https://www.vagrantup.com/
2. Set up a basic `Vagrantfile` for Ubuntu@14.04

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  # Set our box as Ubuntu@14.04 LTS
  # https://atlas.hashicorp.com/ubuntu/boxes/trusty64
  config.vm.box = "ubuntu/trusty64"

  # Give additional memory and CPU to VirtualBox provider
  # https://docs.vagrantup.com/v2/virtualbox/configuration.html
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 2
  end
end
```

3. Start up Vagrant VM via `vagrant up`
4. SSH into VM via `vagrant ssh`
5. Install required dependencies `sudo apt-get install git build-essential`
6. Navigate to shared directory `cd /vagrant` (`/vagrant` is synced directory where `Vagrantfile` is)
7. Run our tests `make test`
8. When everything is all done, VM can be shut down via `vagrant halt` and destroyed via `vagrant destroy`

# Docker
1. Install Docker from here: https://www.docker.com/products/overview
2. Start up a container `docker run -it --volume "$PWD:/vagrant" --name sbp_sandbox ubuntu:14.04 /bin/bash`
    - Docker will auto-fetch our image
    - `-it` tells Docker to connect `/bin/bash` interactively via TTY
    - `--volume` will map our current directory to `/vagrant` in VM (old habit from Vagrant)
3. This will automatically enter our container. If we ever disconnect/want to reconnect, then run `docker exec -it sbp_sandbox /bin/bash`
4. Install required dependencies `sudo apt-get install git build-essential`
5. Navigate to shared directory `cd /vagrant`
6. Run our tests `make test`
7. When everything is all done, our container can be shut down via `docker stop sbp_sandbox` and destroyed via `docker rm sbp_sandbox`. We can also remove the Ubuntu image via `docker rmi ubuntu:14.04`
    - For sanity, we can see all containers via `docker ps --all`
