### ISSUE TITLE
Exit code reporting

### ISSUE THREAD

**Issue by rpdelaney** [twolfson/sexy-bash-prompt#82]
In #80 we will work out how to support opt-in switches for extension. Exit code reporting is planned. For now we can discuss here what it should look like.

I've seen this feature in a few different shell prompts over the years. There are different ways of doing it. A couple things we could try, off the top:

1. A special STATUS_SUCCESS and STATUS_FAILED color that modifies an existing token (like the prompt character [`$`])
2. The same colors that modify a new token, also user-configurable

**Comment by twolfson** [comment]
My gut feeling is we should keep it always white by default (it would be weird to always have a green success prompt for good) and switch to red on error

I concur that we should add an environment variable for color customization like everything else

One concern I have is by running commands, we might modify the exit code or not have access to it in a subshell. We should definitely make sure that's covered by tests

**Comment by twolfson** [comment]
I'm sure that we can look at other prompts as a good point of reference for how to handle not erasing the exit code

**Comment by twolfson** [comment]
Saw this in another bash prompt last week and getting a wild hair to revisit this. I think past attempts have failed due to using `PS1` instead of `PROMPT_COMMAND` which I believe you've mentioned before somewhere

https://github.com/chkhd/bash-prompt/blob/04e2dfa1534b9af807ea67fd3cbdca2a8e48c801/bash-prompt.sh#L104-L106

https://github.com/chkhd/bash-prompt/blob/04e2dfa1534b9af807ea67fd3cbdca2a8e48c801/bash-prompt.sh#L200-L201

**Comment by twolfson** [comment]
Verified once again that using a subshell won't work for exit code passing in `PS1`

Did a broader search, it looks like the convention is to use `PROMPT_COMMAND` to build up `PS1` each time which makes a lot more sense than the `unset` call at the end of the previously linked example

https://stackoverflow.com/a/16715681

https://gist.github.com/weibeld/f3b6e6187029924a9b3d

**Comment by twolfson** [comment]
Lots of promising progress. I think what I botched last time was understanding how to remove the whitespace from PS1 or something (which seems really trivial now). Maybe I was just out of time or something...

No performance or incremental building issues either, I can't recall where we had that issue -- it might have been an alternative filesystem issue

**Comment by twolfson** [comment]
Since we've already got `PROMPT_SYMBOL_COLOR`, going to add in `PROMPT_SYMBOL_ERROR_COLOR`. We can tweak this in the PR if you feel we should also rename `PROMPT_SYMBOL_COLOR` to `PROMPT_SYMBOL_SUCCESS_COLOR` for clarity

**Comment by twolfson** [comment]
Ohhh, the incremental building issue was from me using `echo` inside of `PROMPT_COMMAND` before. This makes a lot more sense to just buffer it all out then dump it via `PS1`

**Comment by twolfson** [comment]
Had a bit of a tangent around consistency where felt we should update `prompt_symbol` logic to be an `_root_symbol` as well but realizing that customization should still be done externally in the script (e.g. use their own `$UID` check if they want to customize for `root` as well)

**Comment by twolfson** [comment]
Huh, TIL `bash` persists the exit code when an empty command is entered. Additionally, I've learned the easiest way to clear that is a `:` (equivalent to a noop)

Still playing around with the format. Showing exit code might be useful, might be annoying indentation-wise. Also might be annoying for any Ctrl+C to show exit code 130

![Selection_216](https://user-images.githubusercontent.com/902488/90683190-fe32f180-e21a-11ea-921b-c335594d5a56.png)

https://www.shell-tips.com/bash/null-command/

**Comment by twolfson** [comment]
Alright, have a version which is PR-ready but kind of want to use this for a few days before opening up the PR. I want to understand more of how annoying a red $ will be whenever something fails -- seems like it could be a nuissance already =/

Going to use the non-number version for now too (there was a blip of a overwriting the $ on Ctrl+r which I can't reproduce)

![Selection_217](https://user-images.githubusercontent.com/902488/90684151-92ea1f00-e21c-11ea-8a26-98fd5bcc0e34.png)

Feel free to use it locally as well, branch is `dev/exit.code`

**Comment by twolfson** [comment]
Yep, it didn't take long before the repeated red despite newline or Ctrl+C got on my nerves. It turns out this was a 2 birds, 1 key solution where we look at the last command + timestamp with `history`

We'll prob need to make this an opt-in/out conditional as some people might expect exit code to accurately be show across multiple new lines (as I'm hiding it technically but it's still accessible via `$?`)

**Comment by twolfson** [comment]
Resolved via #88 and #89. Landed in `1.0.0` (considered `PROMPT_COMMAND` to be major-enough since PS1 might be an API others rely on)

**Comment by twolfson** [comment]
As reported in #90, the usage of `PROMPT_COMMAND` for defining `PS1` prevents extension due to overwriting it on every run. Instead of this, we should define the `PS1` once and then refer to external variables/functions for the exit code detection (updated via a simple `PROMPT_COMMAND`)

Proof of concept can be found here: https://github.com/twolfson/sexy-bash-prompt/issues/90#issuecomment-691387924

**Comment by twolfson** [comment]
This has been resolved once again via #91 and released in `1.1.0`
