### ISSUE TITLE
Error on Mac OS 12.5

### ISSUE THREAD

**Issue by hubefonseca** [twolfson/sexy-bash-prompt#95]
Hi!

I tried to install using the command line, but it does not display correctly, as shown on the image below:

<img width="635" alt="image" src="https://user-images.githubusercontent.com/30186/184708444-5978b625-0db2-4c68-b273-c01f1e550986.png">

**Comment by hubefonseca** [comment]
Forgot to mention that I am using iterm 2, but the result is the same on the classical terminal

![image](https://user-images.githubusercontent.com/30186/184708741-c5215dc9-1f52-4b2e-9913-37b8edd25b89.png)

**Comment by bigfishtoddslivewire** [comment]
I think it's a restricted command now

**Comment by twolfson** [comment]
@hubefonseca It's likely your default shell is `zsh` and not `bash`. You can confirm this via `echo $SHELL`

I've verified I get this behavior if I use `zsh` and `source .bash_prompt` in Docker sandbox:

![image](https://user-images.githubusercontent.com/902488/184786643-d84b3e17-73ac-4242-9833-c62784202d09.png)

You can change the iTerm shell via a profile with a custom shell for `/bin/bash`

https://stackoverflow.com/a/65041741/1960509

You could use a broader change like `chsh` but that feels riskier if there are system level scripts which assume `zsh` instead of `bash`.

If you start receiving a `bash` deprecation notice from macOS, this can be silenced via: `export BASH_SILENCE_DEPRECATION_WARNING=1` in your `.bash_profile`

https://github.com/twolfson/dotfiles/blob/44965bfcff9bf982679f088cd76f1e87a65ab440/.bash_profile#L10-L11
